<?php
/**
 * Featured product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
?>
<div class="widget block featured-products">
	<?php if($params->show_title == 1) : ?>
	<div class="block-title">
		<span <?php //echo $_color_title_box; ?>><?php echo $params->widget_title;?></span>
	</div>
	<?php endif; ?>
	<?php if(!$_featuredCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
	<?php else: ?>
	<div class="block-content">       
		<?php if($params->list_type == 'list'): ?>
		<?php $_iterator = 0; ?>
		<ol class="products-list" id="products-list">
		<?php foreach ($_featuredCollection as $_product): ?>
			<li class="item<?php if( ++$_iterator == sizeof($_featuredCollection) ): ?> last<?php endif; ?>">
				<?php // Product Image ?>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				<?php // Product description ?>
				<div class="product-shop">
					<div class="f-fix">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						
						<?php if($_product->getRatingSummary()): ?>
							<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						
						<?php 
						if($params->show_price == 1) 
						{
							echo $this->getPriceHtml($_product, true);
						} ?>
						
						<div style="clear: both;"></div>
						<?php if($params->show_short_description == 1) : ?>
						<div class="desc std">
							<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<?php endif; ?>
						
						<?php if($params->show_addtocart == 1) : ?>
						<div class="actions">
							<?php if($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
							<?php else: ?>
								<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
								<?php endif; ?>
							</ul>
						</div>
						<?php endif; ?>
					</div>
				</div>
			</li>
		<?php endforeach; ?>
		</ol>
		<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

		<?php elseif($params->list_type == 'grid'): ?>
		<?php  // Grid Mode 
			$_collectionSize = $_featuredCollection->count();
			$_columnCount = $params->featured_products_per_row;
			$pwidth = ' width' . floor (100 / $_columnCount);
			$i = 0; 
		?>
		<?php foreach ($_featuredCollection as $_product) : ?>
			<?php if ($i++%$_columnCount==0): ?>
			<ul class="products-grid">
			<?php endif ?>
				<li class="<?php echo $pwidth; ?> item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
					<div class="spacer">
						<div class="product-image">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(158); ?>" width="158" height="158" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							</a>
							<?php //product percent sale-off
							$firstPrice = (float)$_product->getPrice();
							$finalPrice = (float)$_product->getFinalPrice();
							if ($firstPrice != $finalPrice) :
								if ($finalPrice < $firstPrice) {
									$percent = (($firstPrice - $finalPrice)/$firstPrice) * 100;
								} elseif ($finalPrice > $firstPrice) {
									$percent = (($finalPrice - $firstPrice)/$finalPrice) * 100;
								}
							?>
								<div class="product-sale-off">
									<span class="sale-off-percent"><?php echo number_format($percent, 0); ?>%</span>
									<span class="sale-off-label"><?php echo $this->__('Sale <br> Off'); ?></span>
								</div>
							<?php endif; ?>
						</div>
						<div class="product-more">
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php 
							if($params->show_price == 1) 
							{
								echo $this->getPriceHtml($_product, true);
							} ?>
							<?php if($params->show_addtocart == 1) : ?>
							<div class="actions">
								<?php if($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
								<ul class="add-to-links">
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
									<?php endif; ?>
									<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
									<?php endif; ?>
								</ul>  
							</div> 
							<?php endif; ?>
							<?php if($params->show_short_description == 1) : ?>
								<div class="desc std">
									<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
								</div>
							<?php endif; ?>
						</div>
					</div>
				</li>
			<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
			</ul>
			<?php endif ?>                                       
			<?php endforeach ?>
			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<?php endif; ?>
		<div class="toolbar-bottom">        
			<?php echo $this->getToolbarHtml();?>
		</div>
	</div>
	<?php endif; ?>
</div>
